### ISSUE TITLE
Bot User を potato4d から vuejs-jp-bot に変更する

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/sharin#17]
@re-fort 
あと数日様子見して問題なければこれも vuejs-jp-bot で動かそうと思うので、キーもらえるとありがたいです〜🙏

**Comment by re-fort** [comment]
@potato4d 
slackでDMしました！

**Comment by inouetakuya** [comment]
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/188#issuecomment-500233514

無事に変更できたようなのでクローズします〜。対応ありがとうございました！
