### ISSUE TITLE
環境変数の変更

### ISSUE THREAD

**Issue by aytdm** [vuejs-jp/sharin#23]
Nuxt.js の ドキュメントが置かれているレポジトリが `nuxt/docs` から `nuxt/nuxtjs.org/content` に変更されました。そのため、 sharin の環境変数の一部を以下のように変更したいです。（`nuxt/nuxtjs.org` を `vuejs-jp/ja.nuxtjs.org` として新たに vuejs-jp 配下に fork しました）

```diff
# 検知したい対象のレポジトリを指定
- export SHARIN_UPSTREAM_REPO=nuxt/docs
+ export SHARIN_UPSTREAM_REPO=nuxt/nuxtjs.org
- export SHARIN_UPSTREAM_CHANGED_FILEPATH_STARTS_WITH=en/
+ export SHARIN_UPSTREAM_CHANGED_FILEPATH_STARTS_WITH=content/en/

# Issue を作成したいレポジトリを指定
- export SHARIN_ORIGIN_REPO=vuejs-jp/ja.docs.nuxtjs
+ export SHARIN_ORIGIN_REPO=vuejs-jp/ja.nuxtjs.org
```

@inouetakuya @potato4d 相談ですが、環境変数の変更はどのように行ったらいいでしょうか？以下の点が気になっています。
+ CircleCI 上から直接変更してよいかどうか
+ 変更を私の方でしていいかどうか

**Comment by inouetakuya** [comment]
CircleCI 上から直接変更してよいかどうか -> 良いと思います！（むしろお願いしたいです！） 🙆‍♂️ 
変更を私の方でしていいかどうか -> 良いと思います！（むしろお願いしたいです！） 🙆‍♂️

**Comment by potato4d** [comment]
直接で良いかと！

**Comment by aytdm** [comment]
お二人ともありがとうございます！変更したのでクローズします
